name: 'Tauri Build on Linux'

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
          - platform: 'ubuntu-22.04-arm'
            target: 'aarch64-unknown-linux-gnu'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri app (no bundle)
        run: npx tauri build --no-bundle --target ${{ matrix.target }}
      
      - name: Rename Executable
        run: |
          mv src-tauri/target/${{ matrix.target }}/release/chlaty-player src-tauri/target/${{ matrix.target }}/release/chlaty-player-${{ matrix.target }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chlaty-player-${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/chlaty-player-${{ matrix.target }}
