name: Tauri Build on Linux

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install cross Dependencies
        run: cargo install cross

      - name: Install Additional Cross Dependencies
        run: |
          sudo apt-get update

          # Common tools
          sudo apt-get install -y pkg-config

          sudo apt-get install -y \
            libglib2.0-dev \
            libgtk-3-dev \
            libpango1.0-dev \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV


      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Tauri Build (no bundle)
        run: npx tauri build --no-bundle --target ${{ matrix.target }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chlaty-player-${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/chlaty-player
