name: Tauri Build on Linux

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Tauri Build (no bundle)
        run: npx tauri build --no-bundle --target ${{ matrix.target }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chlaty-player-${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/chlaty-player
