name: Tauri Build on Linux

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install Cross Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libglib2.0-dev
          if [ "${{ matrix.target }}" = "i686-unknown-linux-gnu" ]; then
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y gcc-multilib libglib2.0-dev:i386
          elif [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
            echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          elif [ "${{ matrix.target }}" = "armv7-unknown-linux-gnueabihf" ]; then
            sudo apt-get install -y gcc-arm-linux-gnueabihf
            echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Tauri Build (no bundle)
        run: npx tauri build --no-bundle --target ${{ matrix.target }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chlaty-player-${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/chlaty-player
