name: Tauri Build on macOS

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin     # Intel Macs
          - aarch64-apple-darwin    # Apple Silicon

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Tauri Build (no bundle)
        run: npx tauri build --no-bundle --target ${{ matrix.target }}

      - name: Rename Executable
        run: |
          mv src-tauri/target/${{ matrix.target }}/release/chlaty-player src-tauri/target/${{ matrix.target }}/release/chlaty-player-${{ matrix.target }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chlaty-player-${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/chlaty-player-${{ matrix.target }}
